name = "Colonies"
author = "Or_OS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9988856769ba0eb114ffef55505dbd395cae07bb1f11adddc62795265ca604e"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
