name = "Colonies"
author = "Or_OS"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b546f7642f0ca56eb182a0944b89f470fb0bed8d845d0410b62a0c09c0f7e00b"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
