name = "Colonies"
author = "Or_OS"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e7eaa4cb6c1e9c139ca83a07011254f559d233760167c44cb33e8533322198c"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
