name = "Colonies"
author = "Or_OS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5869b1d8083ac4989e92ca3fb69da1dcd673b841d52c126b01b35581cdd16117"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
