name = "Colonies"
author = "Or_OS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e41bfc1daeb54facfd547cdc335ef87471e639e8cc54552dc102ff70319432b9"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
