name = "Colonies"
author = "Or_OS"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "46c881db4acd0b46d4d98aa081347c289c244a0337b94af946aba28e0c652339"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
