name = "Colonies"
author = "Or_OS"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d32ffb8e9689be32baf678088ab42ec08790370f00c456ce4bdb11cea1c7cc5c"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
