name = "Colonies"
author = "Or_OS"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "930018f60665e40d3b96c6373e2b325c586f69767c5f472195cebcdce840aa28"

[versions]
forge = "36.2.39"
minecraft = "1.16.5"
