name = "Colonies"
author = "Or_OS"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dbb89f68e11ec94aa387c33c38258e16f71b2204ff09c2d275579840c27ec046"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
