name = "Colonies"
author = "Or_OS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9bc162ab5213ccfb4c844e017ce3e30bb387617cf13e6c7f6854377314588a8"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
