name = "Colonies"
author = "Or_OS"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b429d5904e7c8ae5526d6f10545a0605e4c74a7f6686b211e2a72669c0233b0c"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
